services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: research_agent
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data  # pgdata is custome name for storage folder on local machine's hard drive. whereas path specified after : is by default from PostgreSQL for Docker

volumes:
  pgdata:
