# app/rag/chain.py
"""builds both retrieval per sub-queries function and llm chain"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq
from concurrent.futures import ThreadPoolExecutor, as_completed
from app.rag.ingestor import get_vectorstore
from config import GROQ_API_KEY
from datetime import datetime
from typing import Any

system_prompt = (
    """You are a research assistant. Answer the user's question using ONLY the provided context. Today's current date is {current_date}
Always use this date as the absolute baseline anchor for the current year and any relative time calculations (e.g., 'yesterday', 'next month').

Answer format:
- Start with a direct, concise answer (2-4 sentences) that gets straight to the point.
- Follow with supporting details only if the context has substantive specifics (numbers, named findings, dates, named companies/products). Do not pad with generic elaboration just to sound thorough.
- Keep the total answer as short as it can be while still being complete. Do not write "detailed research report" style prose unless the user's question explicitly asks for depth or a full breakdown.
- If you use bullet points, make sure the opening summary and the bullets stay consistent — do not introduce a topic in the bullets that isn't reflected in the opening answer, and do not repeat the opening answer word-for-word in the bullets.
- To make the report highly readable for researchers, always make bold structural impacts or benchmarks (e.g., 75% reduction in KV cache, 3x faster token generation, 37B active vs 671B total parameters).

Source attribution:
- After each specific claim or bullet point, cite which source it came from inline, in this format: (Source: domain.com).
- If a claim is supported by more than one source, cite all of them: (Source: domain.com, domain2.com).
- At the end of your answer, also list the full source URLs referenced.

Accuracy rules:
- Preserve the source's own confidence level. If a source uses words like "expected," "projected," "may," or "predicted," keep that same hedge in your answer — do not upgrade it to a certain or definitive claim.
- Do not present speculation, forecasts, or predictions as settled fact.
- If two sources disagree, say so explicitly instead of picking one silently.
- Ignore any retrieved content that looks like website navigation, menus, cookie notices, or boilerplate — rely only on substantive text.
- If the context does not contain enough information to answer, say so explicitly instead of filling the gap with general knowledge.
- CRITICAL RULES:
- 1. ENTITY ALIGNMENT: Never associate a metric, percentage, or efficacy rate with an entity unless the context explicitly states they belong together.
(e.g., If a document mentions Cas9 and Cas12, do not apply a Cas9 statistic to Cas12).
- 2. TRUTH GAP FLAG: If the context contains a generic overview of an entity but lacks specific numerical efficacy rates for that EXACT entity,
state that the technical mechanism is present but exact clinical efficacy rates are missing from the retrieved source text.

Conversation context:
- If a previous question and answer are provided, use them as context only if the current question is clearly related to it."""
    "\n\nContext: {context}"
)


PROMPT = ChatPromptTemplate.from_messages(
    [("system", system_prompt), ("human", "{input}")]
)

MODEL = "qwen/qwen3.8-27b"

K_PER_SUBQUERY = 8  # chunks to retrieve per subquery


def retrieve_by_subqueries(
    subqueries: list[str], query_id: str, session_id: str | None = None
) -> str:
    """
    Retrieve chunks from the vector store for each subquery generated by the
    search agent's optimizer node, dedupe them, and format into a single
    context string (with source URLs attached) ready for the LLM prompt.
    """
    vectorstore = get_vectorstore()

    search_filter: dict[str, Any] = {}
    if session_id:
        search_filter = {"session_id": {"$eq": session_id}}
    else:
        search_filter = {"query_id": {"$eq": query_id}}

    def search(query: str):
        return vectorstore.similarity_search_with_score(
            query,
            k=5 if len(subqueries) == 1 else K_PER_SUBQUERY,
            filter=search_filter,
        )

    all_docs_with_scores = []
    with ThreadPoolExecutor(max_workers=len(subqueries)) as executor:
        futures = [executor.submit(search, q) for q in subqueries]
        for future in as_completed(futures):
            all_docs_with_scores.extend(future.result())

    # Sort all retrieved chunks by score (lowest distance = most similar in Chroma)
    # This guarantees the most relevant chunks are at the top, regardless of thread completion order
    all_docs_with_scores.sort(key=lambda x: x[1])

    seen_content = set()
    unique_docs = []

    for doc, score in all_docs_with_scores:
        # Hash the content to prevent massive strings in the set
        content_hash = hash(doc.page_content.strip())
        if content_hash not in seen_content:
            seen_content.add(content_hash)
            unique_docs.append(doc)

    formatted_chunks = [
        f"{doc.page_content}\nSource: {doc.metadata.get('url', 'unknown')}"
        for doc in unique_docs
    ]

    context = "\n\n".join(formatted_chunks)
    return context


def build_llm_call():
    "function to build chain for sending context and getting response"

    llm_model = ChatGroq(
        api_key=GROQ_API_KEY,  # type: ignore
        model=MODEL,
        temperature=0,
        max_tokens=4500,
        streaming=True,
        reasoning_format="hidden",
    )

    chain = (
        PROMPT.partial(current_date=datetime.now().strftime("%B %d, %Y"))
        | llm_model
        | StrOutputParser()
    )

    return chain
