# app/rag/chain.py
"""builds both retrieval per sub-queries function and llm chain"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq
from concurrent.futures import ThreadPoolExecutor, as_completed
from app.rag.ingestor import get_vectorstore
from config import GROQ_API_KEY
from datetime import datetime

current_date = datetime.now().strftime("%B %d, %Y")

system_prompt = (
    f"""You are a research assistant. Answer the user's question using ONLY the provided context. Today's current date is {current_date}
Always use this date as the absolute baseline anchor for the current year and any relative time calculations (e.g., 'yesterday', 'next month').

Answer format:
- Start with a direct, concise answer (2-4 sentences) that gets straight to the point.
- Follow with supporting details only if the context has substantive specifics (numbers, named findings, dates, named companies/products). Do not pad with generic elaboration just to sound thorough.
- Keep the total answer as short as it can be while still being complete. Do not write "detailed research report" style prose unless the user's question explicitly asks for depth or a full breakdown.
- If you use bullet points, make sure the opening summary and the bullets stay consistent — do not introduce a topic in the bullets that isn't reflected in the opening answer, and do not repeat the opening answer word-for-word in the bullets.

Source attribution:
- After each specific claim or bullet point, cite which source it came from inline, in this format: (Source: domain.com).
- If a claim is supported by more than one source, cite all of them: (Source: domain.com, domain2.com).
- At the end of your answer, also list the full source URLs referenced.

Accuracy rules:
- Preserve the source's own confidence level. If a source uses words like "expected," "projected," "may," or "predicted," keep that same hedge in your answer — do not upgrade it to a certain or definitive claim.
- Do not present speculation, forecasts, or predictions as settled fact.
- If two sources disagree, say so explicitly instead of picking one silently.
- Ignore any retrieved content that looks like website navigation, menus, cookie notices, or boilerplate — rely only on substantive text.
- If the context does not contain enough information to answer, say so explicitly instead of filling the gap with general knowledge.

Conversation context:
- If a previous question and answer are provided, use them as context only if the current question is clearly related to it."""
    "Context: {context}"
)


PROMPT = ChatPromptTemplate.from_messages(
    [("system", system_prompt), ("human", "{input}")]
)

MODEL = "qwen/qwen3.6-27b"

K_PER_SUBQUERY = 2  # chunks to retrieve per subquery


def retrieve_by_subqueries(subqueries: list[str], session_id: str | None = None) -> str:
    """
    Retrieve chunks from the vector store for each subquery generated by the
    search agent's optimizer node, dedupe them, and format into a single
    context string (with source URLs attached) ready for the LLM prompt.
    """
    vectorstore = get_vectorstore()

    search_kwargs = {}
    if session_id is not None:
        search_kwargs["filter"] = {"session_id": session_id}

    def search(query: str):
        return vectorstore.similarity_search(
            query, k=5 if len(subqueries) == 1 else K_PER_SUBQUERY, **search_kwargs
        )

    all_docs = []
    with ThreadPoolExecutor(max_workers=len(subqueries)) as executor:
        futures = [executor.submit(search, q) for q in subqueries]
        for future in as_completed(futures):
            all_docs.extend(future.result())

    # dedupe using (url, content) instead of doc.id, since doc.id can be
    # None/unreliable depending on how documents were ingested
    seen_id = set()
    unique_docs = []
    for doc in all_docs:
        if doc.id not in seen_id:
            seen_id.add(doc.id)
            unique_docs.append(doc)

    # format each chunk WITH its source url, so the LLM can actually cite it
    formatted_chunks = [
        f"{doc.page_content}\nSource: {doc.metadata.get('url', 'unknown')}"
        for doc in unique_docs
    ]

    context = "\n\n".join(formatted_chunks)
    return context


def build_llm_call():
    "function to build chain for sending context and getting response"

    llm_model = ChatGroq(
        api_key=GROQ_API_KEY,  # type: ignore
        model=MODEL,
        temperature=0,
        max_tokens=4500,
        streaming=True,
        reasoning_format="hidden",
    )

    chain = PROMPT | llm_model | StrOutputParser()

    return chain
